name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Allow GitHub Actions to create and approve deployments
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Create config.json from secrets
        run: |
          echo '{
            "github_token": "${{ secrets.GITHUB_TOKEN || '' }}",
            "repo_owner": "${{ secrets.REPO_OWNER || '' }}",
            "repo_name": "${{ secrets.REPO_NAME || '' }}",
            "github_enterprise_url": "${{ secrets.GITHUB_ENTERPRISE_URL || '' }}"
          }' > config.json

          echo "Generated config.json:"
          cat config.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
