name: Build and Deploy to Production

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create .env file from secrets
        run: |
          echo "VITE_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN || '' }}" >> .env
          echo "VITE_REPO_OWNER=${{ secrets.REPO_OWNER || '' }}" >> .env
          echo "VITE_REPO_NAME=${{ secrets.REPO_NAME || '' }}" >> .env
          echo "VITE_GITHUB_ENTERPRISE_URL=${{ secrets.GITHUB_ENTERPRISE_URL || '' }}" >> .env

      - name: Build SvelteKit app
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
