name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: "preview-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create .env file from secrets
        run: |
          echo "VITE_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN || '' }}" >> .env
          echo "VITE_REPO_OWNER=${{ secrets.REPO_OWNER || '' }}" >> .env
          echo "VITE_REPO_NAME=${{ secrets.REPO_NAME || '' }}" >> .env
          echo "VITE_GITHUB_ENTERPRISE_URL=${{ secrets.GITHUB_ENTERPRISE_URL || '' }}" >> .env

      - name: Build SvelteKit app
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files-${{ github.event.number || github.sha }}
          path: build/
          retention-days: 7

  comment-preview:
    runs-on: ubuntu-latest
    needs: build-preview
    steps:
      - name: Comment PR with build info
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('🚀 Build completed')
            );
            
            const prNumber = context.issue.number;
            const branchName = context.payload.pull_request.head.ref;
            const commitSha = context.payload.pull_request.head.sha.substring(0, 7);
            
            const commentBody = `🚀 **Build completed successfully!**
            
            **PR #${prNumber}** - Branch: \`${branchName}\`
            **Commit:** \`${commitSha}\`
            
            **Build artifacts:** Available for download from the Actions tab
            **Production URL:** https://${context.repo.owner}.github.io/${context.repo.repo}/
            
            To test locally:
            \`\`\`bash
            git checkout ${branchName}
            yarn install
            yarn dev
            \`\`\`
            
            ---
            *This comment was automatically generated by GitHub Actions.*`;
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
            }
